[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/apps/nvim"]
    type = "archive"
    url = "https://github.com/neovim/neovim/releases/download/v0.9.0/nvim-linux64.tar.gz"
    exact = true
    stripComponents = 1
    checksum.sha256 = "fa93f06bec111fea6f316f186b96e19ba289a2dca2d0731e23597398b7397c8f"
[".local/apps/lazygit"]
   type = "archive"
   url = "https://github.com/jesseduffield/lazygit/releases/download/v0.37.0/lazygit_0.37.0_Linux_x86_64.tar.gz"
   exact = true
   checksum.sha256 = "f801f5a7ab6111fc9a97b3ca7597474b672c8d0d16a3e29d7c6005f5ec9257a9"
